<?
use Icinga\Module\Monitoring\Object\Service;
use Icinga\Module\Monitoring\Object\Host;


?>

<div class="controls">
  <?php if (! $this->compact): ?>
    <?= $tabs; ?>
  <?php endif ?>
</div>


<div class="content">

    <h1>Boxy Dashboard</h1>
    <h4>Host: <span id="boxy_host"></span></h4>
    <h4>Service: <span id="boxy_svc"></span></h4>
    <? if ($this->showlegend){ ?>
    <div class="boxy_legend">
        <span class="boxy_sublegend">
            <span class="legendtext">&#10004; = Acknowledged</span>
            <span class="legendtext">&#9201; = In Downtime</span>
            <span class="legendtext">&#8632; = Host Issue Acknowledged</span>
        </span>
        <span class="boxy_sublegend">
            <h4 class="legendtext">Status:</h4>
            <span class="boxy_legend_box ok" >ok</span>
            <span class="boxy_legend_box warning" >warning</span>
            <span class="boxy_legend_box critical" >critical</span>
            <span class="boxy_legend_box unknown" >unknown</span>
        </span>
        <span class="boxy_sublegend">
            <h4 class="legendtext" >Acknowledged:</h4>
            <span class="boxy_legend_box warning-ack" >warning</span>
            <span class="boxy_legend_box critical-ack" >critical</span>
            <span class="boxy_legend_box unknown-ack" >unknown</span>
        </span>
    </div>
    <? } ?>
<h2>Host Info</h2>
<?
$size=$this->boxsize;
$font_size=number_format($size * 0.65, 0);
foreach ($this->hosts as $host){
    $title = htmlspecialchars($host->{'host_display_name'});
    $content="&nbsp;";
    $returncode=$host->{'host_state_text'};
    if ($host->{'host_acknowledged'}==1 ){
        $returncode.="-ack";
        $content= "&#10004;";
        $title.=" (Acknowledged)";
    }?>
    <a href='<?= $this->path_prefix ?>/monitoring/host/show?host=<?=$host->{'host_name'}?>' class='boxy_box host state <?=$returncode?>' style='width:<?=$size?>px; height:<?=$size?>px; font-size:<?=$font_size?>px;' title="<?=$title?>"><?=$content?></a>
<? } ?>

<br clear="all"/>
<h2>Service Info</h2>

<? foreach ($this->services as $service){
    $service->{'service_hard_state'} = ($service->{'service_hard_state'}) ? "hard" : "soft";
    $title = $service->{'host_display_name'}.": ".$service->{'service_description'};
    #."(".$service->{'current_check_attempt'} .",".$service->{'max_check_attempts'} .")(". $service->{'service_hard_state'}.")+acked:".$service->{'service_acknowledged'} ;
    $content="&nbsp;";
    $returncode=$service->{'service_state_text'};
    if ($service->{'service_in_downtime'}==1 or $service->{'host_in_downtime'}==1 ){
        $returncode.="-downtime";
        $content= "&#9201;";
        $title.=" (Scheduled Maintenance)";
    }elseif ($service->{'service_acknowledged'}==1 ){
        $returncode.="-ack";
        $content= "&#10004;";
        $title.=" (Acknowledged)";
    }elseif ($service->{'service_state_text'} != "ok"  && $service->{'host_acknowledged'} == 1 ){
        $returncode.="-ack";
        $content= "&#8632;";
        $title.=" (Host Issue Acknowledged)";
    }
    $title=htmlspecialchars($title."\n ".$service->{'service_output'});?>
    <a href='<?= $this->path_prefix ?>/monitoring/service/show?host=<?=$service->{'host_name'}?>&service=<?=$service->{'service_description'}?>' class='boxy_box service state <?=$returncode?>' style='width:<?=$size?>px; height:<?=$size?>px; font-size:<?=$font_size?>px;' title="<?=$title?>"><?=$content?></a>

<? } ?>
<br clear=all>
<pre style="font-size:20px"><?=$this->debug?></pre>
</div>
